import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import NavbarComponent from "@/components/UI/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Whispering Winds",
  description: "Generated by MR-Kuen",
  icons: [
    {
      rel: "icon",
      url: "/favicon.ico",
      sizes: "256x256",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{/* Metadata and links to stylesheets or scripts go here */}</head>
      <body className={inter.className}>
        <NextUIProvider>
          {/* <NavbarComponent /> */}
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
